// Generates src/data/faCatalog.ts from the installed Font Awesome Free metadata.
//
// WHY a committed, pregenerated module: the FA metadata (icon-families.json) is
// ~4.7MB and includes SVG paths we never need. We distill it to a compact list
// (name + free styles + search terms) so the picker has the full FA Free 6.4.2
// catalog without bundling the raw metadata. Re-run only when bumping FA:
//   npm run gen:fa
//
// The output is committed so `npm run build` needs no generation step or network.
// Pin must match the live site's FA version (currently Free 6.4.2).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const META = resolve(root, 'node_modules/@fortawesome/fontawesome-free/metadata/icon-families.json')
const OUT = resolve(root, 'src/data/faCatalog.ts')

const PKG = JSON.parse(
  readFileSync(resolve(root, 'node_modules/@fortawesome/fontawesome-free/package.json'), 'utf8'),
)
const VERSION = PKG.version

// FA Free ships only the "classic" family; map its styles to our shorthand.
const STYLE_SHORT = { solid: 's', regular: 'r', brands: 'b' }
const STYLE_ORDER = { s: 0, r: 1, b: 2 }
const MAX_TERMS = 10

const meta = JSON.parse(readFileSync(META, 'utf8'))

const icons = []
for (const [name, entry] of Object.entries(meta)) {
  const free = entry.familyStylesByLicense?.free ?? []
  // Only classic-family free styles are renderable by the site's all.min.css.
  const styles = [
    ...new Set(
      free
        .filter(fs => fs.family === 'classic' && STYLE_SHORT[fs.style])
        .map(fs => STYLE_SHORT[fs.style]),
    ),
  ].sort((a, b) => STYLE_ORDER[a] - STYLE_ORDER[b])
  if (styles.length === 0) continue // pro-only icon — exclude

  // Search terms: the FA terms plus the label, lowercased, deduped, minus the
  // name itself (the picker already searches on name). Capped to bound file size.
  const terms = [...new Set([...(entry.search?.terms ?? []), entry.label ?? ''].map(t => String(t).toLowerCase().trim()))]
    .filter(t => t && t !== name)
    .slice(0, MAX_TERMS)

  icons.push({ n: name, t: terms, s: styles })
}

icons.sort((a, b) => a.n.localeCompare(b.n))

const lines = icons.map(i => `  ${JSON.stringify(i)},`).join('\n')
const out = `// AUTO-GENERATED by scripts/genFaCatalog.mjs from Font Awesome Free ${VERSION}.
// Do not edit by hand. Re-run \`npm run gen:fa\` after bumping the FA version.
// ${icons.length} free icons. Lazy-imported by IconPicker so it stays a separate chunk.

// s = solid (fa-solid), r = regular (fa-regular), b = brands (fa-brands)
export type FaStyle = 's' | 'r' | 'b'

export interface FaIcon {
  /** icon slug, e.g. "house" -> fa-house */
  n: string
  /** search terms (lowercased, excludes the name) */
  t: string[]
  /** available free styles, in s,r,b order */
  s: FaStyle[]
}

export const FA_VERSION = '${VERSION}'

export const FA_STYLE_PREFIX: Record<FaStyle, string> = {
  s: 'fa-solid',
  r: 'fa-regular',
  b: 'fa-brands',
}

export const FA_CATALOG: FaIcon[] = [
${lines}
]
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, out)
console.log(`Wrote ${icons.length} icons to ${OUT} (FA ${VERSION})`)
